server:
  port: 8888

spring:
  application:
    name: processor
  cloud:
    gcp:
      datastore:
        project-id: true-server-259316
        credentials:
          location: classpath:key.json




iExCloudServer: https://sandbox.iexapis.com/stable/
# https://sandbox.iexapis.com/stable/stock/aapl/company?token=Tsk_a29d14855d4c4ac5b8bc51a86ea05b44
# https://sandbox.iexapis.com/stable/ref-data/symbols?token=Tsk_a29d14855d4c4ac5b8bc51a86ea05b44
  #

iExCloudSymbols: ref-data/symbols?token=

iExCloudToken: Tsk_a29d14855d4c4ac5b8bc51a86ea05b44
#pk_51dc0716d4f646d4bb8cad7e57f5bf4d

iExCloudPrice: stock/twtr/price?token=


#prices
#https://sandbox.iexapis.com/stable/stock/twtr/price?token=Tsk_a29d14855d4c4ac5b8bc51a86ea05b44

